services:
  - type: web
    name: yolo-streamlit-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run h.py --server.port=10000 --server.enableCORS=false
    plan: free
    region: oregon
    branch: main
    autoDeploy: true
