services:
  - type: web
    name: yolo-streamlit-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run h.py --server.enableCORS=false --server.enableXsrfProtection=false
    plan: free
    region: oregon
    branch: main
    autoDeploy: true
